ULA_TB.v
ULA.v
src/BitSlice.v
src/utils/Or4.v
src/utils/And4.v
src/circuito_somador/CircuitoSomador.v
src/circuito_somador/SomadorCompleto.v
src/circuito_somador/Complemento2.v
src/circuito_somador/MeioSomador.v
